- name: Grafana and Prometheus
  hosts:  localhost
  tasks:
    - name: add repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: update repo
      command: helm repo update

    - name: install prometheustask
      command: helm install monitoring prometheus-community/kube-prometheus-stack
