- name: Deploy Application to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Deployment
      k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: default
            name: my-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                  - name: my-app
                    image: hoanghp/web-nodejs
                    ports:
                      - containerPort: 3000
    - name: Apply Service
      k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: default
            name: my-app
          spec:
            selector:
              app: my-app
            ports:
              - protocol: TCP
                port: 80
                targetPort: 3000

